var namespace_smart_localization_1_1_editor =
[
    [ "AndroidStorePresenceGenerator", "class_smart_localization_1_1_editor_1_1_android_store_presence_generator.html", "class_smart_localization_1_1_editor_1_1_android_store_presence_generator" ],
    [ "CSVExporter", "class_smart_localization_1_1_editor_1_1_c_s_v_exporter.html", "class_smart_localization_1_1_editor_1_1_c_s_v_exporter" ],
    [ "CSVExportWindow", "class_smart_localization_1_1_editor_1_1_c_s_v_export_window.html", "class_smart_localization_1_1_editor_1_1_c_s_v_export_window" ],
    [ "CSVImportWindow", "class_smart_localization_1_1_editor_1_1_c_s_v_import_window.html", "class_smart_localization_1_1_editor_1_1_c_s_v_import_window" ],
    [ "CSVUpdateWindow", "class_smart_localization_1_1_editor_1_1_c_s_v_update_window.html", "class_smart_localization_1_1_editor_1_1_c_s_v_update_window" ],
    [ "CustomResxImporter", "class_smart_localization_1_1_editor_1_1_custom_resx_importer.html", "class_smart_localization_1_1_editor_1_1_custom_resx_importer" ],
    [ "DirectoryUtility", "class_smart_localization_1_1_editor_1_1_directory_utility.html", "class_smart_localization_1_1_editor_1_1_directory_utility" ],
    [ "EditRootLanguageFileWindow", "class_smart_localization_1_1_editor_1_1_edit_root_language_file_window.html", "class_smart_localization_1_1_editor_1_1_edit_root_language_file_window" ],
    [ "FileUtility", "class_smart_localization_1_1_editor_1_1_file_utility.html", "class_smart_localization_1_1_editor_1_1_file_utility" ],
    [ "IAutomaticTranslator", "interface_smart_localization_1_1_editor_1_1_i_automatic_translator.html", "interface_smart_localization_1_1_editor_1_1_i_automatic_translator" ],
    [ "IOSStorePresenceGenerator", "class_smart_localization_1_1_editor_1_1_i_o_s_store_presence_generator.html", "class_smart_localization_1_1_editor_1_1_i_o_s_store_presence_generator" ],
    [ "LanguageDictionaryHelper", "class_smart_localization_1_1_editor_1_1_language_dictionary_helper.html", "class_smart_localization_1_1_editor_1_1_language_dictionary_helper" ],
    [ "LanguageHandlerEditor", "class_smart_localization_1_1_editor_1_1_language_handler_editor.html", "class_smart_localization_1_1_editor_1_1_language_handler_editor" ],
    [ "LocalizationWindowUtility", "class_smart_localization_1_1_editor_1_1_localization_window_utility.html", "class_smart_localization_1_1_editor_1_1_localization_window_utility" ],
    [ "LocalizationWorkspace", "class_smart_localization_1_1_editor_1_1_localization_workspace.html", "class_smart_localization_1_1_editor_1_1_localization_workspace" ],
    [ "LocalizedAudioSourceInspector", "class_smart_localization_1_1_editor_1_1_localized_audio_source_inspector.html", "class_smart_localization_1_1_editor_1_1_localized_audio_source_inspector" ],
    [ "LocalizedGUITextInspector", "class_smart_localization_1_1_editor_1_1_localized_g_u_i_text_inspector.html", "class_smart_localization_1_1_editor_1_1_localized_g_u_i_text_inspector" ],
    [ "LocalizedGUITextureInspector", "class_smart_localization_1_1_editor_1_1_localized_g_u_i_texture_inspector.html", "class_smart_localization_1_1_editor_1_1_localized_g_u_i_texture_inspector" ],
    [ "LocalizedKeySelector", "class_smart_localization_1_1_editor_1_1_localized_key_selector.html", "class_smart_localization_1_1_editor_1_1_localized_key_selector" ],
    [ "MicrosoftAutomaticTranslator", "class_smart_localization_1_1_editor_1_1_microsoft_automatic_translator.html", "class_smart_localization_1_1_editor_1_1_microsoft_automatic_translator" ],
    [ "SerializableLocalizationObjectPair", "class_smart_localization_1_1_editor_1_1_serializable_localization_object_pair.html", "class_smart_localization_1_1_editor_1_1_serializable_localization_object_pair" ],
    [ "SerializableStringPair", "class_smart_localization_1_1_editor_1_1_serializable_string_pair.html", "class_smart_localization_1_1_editor_1_1_serializable_string_pair" ],
    [ "SmartCultureInfoEx", "class_smart_localization_1_1_editor_1_1_smart_culture_info_ex.html", "class_smart_localization_1_1_editor_1_1_smart_culture_info_ex" ],
    [ "SmartLocalizationWindow", "class_smart_localization_1_1_editor_1_1_smart_localization_window.html", "class_smart_localization_1_1_editor_1_1_smart_localization_window" ],
    [ "StringExtensions", "class_smart_localization_1_1_editor_1_1_string_extensions.html", "class_smart_localization_1_1_editor_1_1_string_extensions" ],
    [ "TranslateLanguageWindow", "class_smart_localization_1_1_editor_1_1_translate_language_window.html", "class_smart_localization_1_1_editor_1_1_translate_language_window" ]
];